default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
        args: [--skip-string-normalization]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --ignore-init-module-imports
          - --remove-all-unused-imports
          - --remove-duplicate-keys
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
      - id: trailing-whitespace
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: (^(dev/|config/|addons_ext/|addons_repos_ext/)|/__init__\.py$)
        additional_dependencies: ["flake8-bugbear==21.4.3"]
        args: [--config, dev/.flake8]
      - id: flake8
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
        name: flake8 only __init__.py
        args: [--config, dev/.flake8, "--extend-ignore=F401"] # ignore unused imports in __init__.py
        files: /__init__\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort except __init__.py
        exclude: /__init__\.py$
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
        args: ["--in-place", "--wrap-summaries=88"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        exclude: ^(dev/|config/|addons_ext/|addons_repos_ext/)
        args: ["--py39-plus"]
