version: '3.1'
services:
  odoo:
    platform: linux/amd64
    container_name: ${PROJECT_CODE:-BASE}-ODOO
    build: .
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons_themes:/mnt/themes
      - ./addons_bp:/mnt/addons_bp
      - ./addons_ext:/mnt/addons_ext
      - ./addons_repos_ext:/mnt/addons_repos_ext
  db:
    container_name: ${PROJECT_CODE:-BASE}-DB
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: ${PROJECT_CODE:-BASE}-PGADMIN
    image: dpage/pgadmin4:6.14
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@bloopark.de
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-8099}:80"
    tty: true
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/pgpass:/pgadmin4/pgpass
    links:
      - "db:psql-server"
volumes:
  odoo-data:
  postgres-data:
  pgadmin-data:
